management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    enabled: true
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    filter-method: servlet
    filter-order: -10
    url: .*
    metrics:
      tags:
      - key: USERNAME
        expression: "@securityService.username() != null ? @securityService.username() : 'anonym'"
        types: REJECTED_COUNTER
      - key: URL
        expression: getRequestURI()
    rate-limits:
    - bandwidths:
      - capacity: 30
        time: 1
        unit: minutes
  - cache-name: buckets   
    filter-method: servlet
    filter-order: 1
    url: .*
    metrics:
      tags:
        - key: USERNAME
          expression: "@securityService.username() != null ? @securityService.username() : 'anonym'"
        - key: URL
          expression: getRequestURI()
    rate-limits:
    - execute-condition:  "@securityService.username() == 'admin'"
      expression: "@securityService.username()?: getRemoteAddr()"
      bandwidths:
      - capacity: 30
        time: 1
        unit: minutes
    - execute-condition: "@securityService.username() != 'admin'"
      expression: "@securityService.username()?: getRemoteAddr()"
      bandwidths:
      - capacity: 30
        time: 1
        unit: minutes